_description: |
  A simple layout.

head:
  _componentList:
    page: true
    include:
      - meta-site
      - meta-title
      - meta-url
      - meta-description
      - meta-keywords
      - meta-authors
      - meta-image

headLayout:
  _componentList:
    include:
      - meta-site
      - meta-icons
top:
  _componentList:
    include:
      - header
      - vulture-section
      - magazine-section

main:
  _placeholder:
    text: Main Section
    height: 1000px
  _componentList:
    page: true
    fuzzy: true
    include: []

side:
  _componentList:
    include:
      - advertisement
      - most-viewed-stories

bottom:
  _componentList:
    include:
      - footer
      - vulture-section

kilnInternals:
  _componentList:
    internals: true
    include:
      - clay-kiln
