_description:
  most view stories articles

stories:
  _placeholder:
    height: 50px
    text: New story
    required: true
  _has:
    input: complex-list
    validate:
      - min: 1
      - max: 5
      - required: true
    props:
      -
        prop: title
        _has:
          input: text
      -
        prop: url
        _has:
          input: text
          type: url

_groups:
  settings:
    fields:
      - stories