_description:
  Articles suggestion component

imageUrl:
  _has:
    input: text
    type: url

title:
  _has:
    input: text

author:
  _has:
    input: text

_groups:
  settings:
    fields:
      - title
      - author
      - imageUrl