_description:
  Side gallery component

gallery:
  _has:
    input: complex-list
    props:
      -
        prop: image
        _label: imageUrl
        _has:
          input: text
          type: url

_groups:
  settings:
    fields:
      - gallery
    _placeholder:
      height: 50px
      text: New side gallery
      ifEmpty: gallery