_description:
  Different gallery photo component

gallery:
  _placeholder:
    height: 50px
    text: New carousel
    required: true
  _has:
    input: complex-list
    props:
      -
        prop: image
        _label: imageUrl
        _has:
          input: text
          type: url
      -
        prop: title
        _label: imageTitle
        _has:
          input: text

ledeImage:
  _has:
    input: text
    type: url

_groups:
  settings:
    fields:
    - ledeImage
    - gallery