_description: |
  Adds `<meta name="description">` tags to the head.

description:
  _label: Description
  _subscribe: pageDescription
  _has:
    input: text
    help: Description of the content on this page, used by search engines.
    # validate: # TODO: make required when we have an approach for article metadata
    #   required: true

_groups:
  settings:
    fields:
      - description
